name: flutter_hookz
description: Utility hooks for Flutter, based on flutter_hooks
version: 0.1.0
repository: https://github.com/timosg/flutter_hookz/tree/main
issue_tracker: https://github.com/timosg/flutter_hookz/issues
homepage: https://github.com/timosg/flutter_hookz

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter_hooks: ^0.21.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0